#!/usr/bin/env bash
set -euo pipefail
umask 077
backup_dir="$HOME/.local/share/myserver/backups"
mkdir -p "$backup_dir"
python3 -S cli.py backup-full "$backup_dir/myserver-$(date -u +%Y%m%d-%H%M%S).tar"
# Only rotate backups generated by this script after today's backup succeeded.
find "$backup_dir" -maxdepth 1 -type f \( -name 'myserver-????????-??????.sqlite' -o -name 'myserver-????????-??????.tar' \) -mtime +30 -delete
